In [3]:
import torch

In [4]:
from torch.nn import *

In [13]:
timage = torch.rand((1,3,224,224))

In [15]:
timage.shape

torch.Size([1, 3, 224, 224])

In [17]:
conv1 = Conv2d(in_channels=3, out_channels=64, kernel_size = (3,3), padding = 'same')
timage1 = conv1(timage)
timage1.shape

torch.Size([1, 64, 224, 224])

In [19]:
conv2 = Conv2d(in_channels=64, out_channels=64, kernel_size = (3,3), padding = 'same')
timage2 = conv2(timage1)
timage2.shape

torch.Size([1, 64, 224, 224])

In [22]:
pool2 = MaxPool2d((2,2), stride = 2)
timage3 = pool2(timage2)
timage3.shape

torch.Size([1, 64, 112, 112])

In [23]:
conv4 = Conv2d(in_channels=64, out_channels=128, kernel_size = (3,3), padding = 'same')
timage4 = conv4(timage3)
timage4.shape

torch.Size([1, 128, 112, 112])

In [24]:
conv5 = Conv2d(in_channels=128, out_channels=128, kernel_size = (3,3), padding = 'same')
timage5 = conv5(timage4)
timage5.shape

torch.Size([1, 128, 112, 112])

In [25]:
pool6 = MaxPool2d((2,2), stride = 2)
timage6 = pool6(timage5)
timage6.shape

torch.Size([1, 128, 56, 56])

In [26]:
conv7 = Conv2d(in_channels=128, out_channels=256, kernel_size = (3,3), padding = 'same')
timage7 = conv7(timage6)
timage7.shape

torch.Size([1, 256, 56, 56])

In [30]:
up8 = Upsample((112,112))
timage8 = up8(timage7)
timage8.shape

torch.Size([1, 256, 112, 112])

In [52]:
timage9.shape

torch.Size([1, 128, 112, 112])

In [51]:
timage5.shape

torch.Size([1, 128, 112, 112])

In [55]:
timage21 = torch.concat((timage5, timage9), dim =1)
timage21.shape

torch.Size([1, 256, 112, 112])

In [31]:
conv8 = Conv2d(in_channels=256, out_channels=128, kernel_size = (3,3), padding = 'same')
timage9 = conv8(timage8)
timage9.shape

torch.Size([1, 128, 112, 112])

In [32]:
up10 = Upsample((224, 224))
timage10 = up10(timage9)
timage10.shape

torch.Size([1, 128, 224, 224])

In [33]:
conv11 = Conv2d(in_channels=128, out_channels=64, kernel_size = (3,3), padding = 'same')
timage11 = conv11(timage10)
timage11.shape

torch.Size([1, 64, 224, 224])

In [34]:
conv13 = Conv2d(in_channels=64, out_channels=2, kernel_size = (1,1), padding = 'same')
timage13 = conv13(timage11)
timage13.shape

torch.Size([1, 2, 224, 224])

In [35]:
timage13

tensor([[[[0.0819, 0.0831, 0.0825,  ..., 0.0738, 0.0725, 0.0752],
          [0.0826, 0.0836, 0.0818,  ..., 0.0731, 0.0729, 0.0811],
          [0.0852, 0.0811, 0.0771,  ..., 0.0718, 0.0724, 0.0805],
          ...,
          [0.0802, 0.0794, 0.0801,  ..., 0.0816, 0.0779, 0.0788],
          [0.0807, 0.0826, 0.0849,  ..., 0.0871, 0.0819, 0.0816],
          [0.0811, 0.0828, 0.0842,  ..., 0.0858, 0.0823, 0.0829]],

         [[0.1261, 0.1313, 0.1305,  ..., 0.1302, 0.1306, 0.1241],
          [0.1323, 0.1415, 0.1411,  ..., 0.1349, 0.1341, 0.1238],
          [0.1315, 0.1414, 0.1411,  ..., 0.1314, 0.1308, 0.1221],
          ...,
          [0.1329, 0.1393, 0.1391,  ..., 0.1259, 0.1244, 0.1297],
          [0.1334, 0.1395, 0.1400,  ..., 0.1280, 0.1274, 0.1300],
          [0.1350, 0.1378, 0.1395,  ..., 0.1297, 0.1294, 0.1304]]]],
       grad_fn=<ThnnConv2DBackward0>)

In [37]:
final = Softmax(dim=1)
timage14 = final(timage13)
timage14.shape

torch.Size([1, 2, 224, 224])

In [47]:
timage15 = torch.max(timage14, dim =1, keepdim=True)

In [49]:
timage15.indices

tensor([[[[1, 1, 1,  ..., 1, 1, 1],
          [1, 1, 1,  ..., 1, 1, 1],
          [1, 1, 1,  ..., 1, 1, 1],
          ...,
          [1, 1, 1,  ..., 1, 1, 1],
          [1, 1, 1,  ..., 1, 1, 1],
          [1, 1, 1,  ..., 1, 1, 1]]]])

In [57]:
testa = torch.rand((2,3,4,5))

In [58]:
testa.shape

torch.Size([2, 3, 4, 5])

In [61]:
testa.transpose(1,2).transpose(2,3).shape

torch.Size([2, 4, 5, 3])

In [41]:
timage14[0][:,12, 76]

tensor([0.4854, 0.5146], grad_fn=<SelectBackward0>)

In [12]:
import pandas as pd

In [20]:
testa = pd.DataFrame(index = ['Mary', 'John', 'Larry'], columns = ['name', 'first', 'second'])

In [30]:
testa['first']['John'] =2

In [31]:
testa

name first second
Mary   NaN   NaN    NaN
John   NaN     2    NaN
Larry  NaN   NaN    NaN

In [32]:
testa['name']['John'] = 30
testa['name']['Mary'] = 20

In [33]:
testa

name first second
Mary    20   NaN    NaN
John    30     2    NaN
Larry  NaN   NaN    NaN

In [39]:
testa.loc('first' == 2)

In [1]:
import numpy as np

In [2]:
testa = np.arange(-1,1,1/1000)

In [23]:
np.sqrt(1-(testa**2))

array([0.        , 0.04471018, 0.06321392, ..., 0.07740155, 0.06321392,
       0.04471018])

In [7]:
testa.shape

(2000,)

In [20]:
[-3,5][random.randrange(2)]

5

In [10]:
import random

In [24]:
import torch

In [29]:
np.cos(torch.distributions.Uniform(-np.pi, +np.pi).sample((5,)))

tensor([-0.0050,  0.7370, -0.6204, -0.6802, -0.9934])